---
.travis.yml:
  secure: "hz3gZgI7pMtV6H4m2T1Y418bJ0puwSir2j7oWdkDjB0YjSMwHERvQbbxxfLa47Y/sN2RKo7f5fzMFudriqkw75zyUtnpe4UWITVmQ8DkOQc/G0xb2aCOdenV2CEWZ1fQloL2/n5dYlMgw22iXgb2ARCjhgLYUZG2A9XDKQaQSUk="
spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_methods'"
spec/acceptance/nodesets/docker/centos-5.yml:
  delete: true
spec/acceptance/nodesets/docker/centos-6.yml:
  delete: true
spec/acceptance/nodesets/docker/centos-7.yml:
  delete: true
spec/acceptance/nodesets/docker/debian-7.yml:
  delete: true
spec/acceptance/nodesets/docker/debian-8.yml:
  delete: true
spec/acceptance/nodesets/docker/ubuntu-12.04.yml:
  delete: true
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
  delete: true
spec/acceptance/nodesets/docker/ubuntu-16.04.yml:
  delete: true
spec/acceptance/nodesets/centos-511-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-72-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-78-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-82-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  delete: true
